name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        DOCKER_TAG_PREFIX: main
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build . --file Dockerfile --tag ladartha/portalum-pdf-generator:$DOCKER_TAG_PREFIX-$GITHUB_RUN_NUMBER --tag ladartha/portalum-pdf-generator:latest
        docker push ladartha/portalum-pdf-generator:$DOCKER_TAG_PREFIX-$GITHUB_RUN_NUMBER
        docker push ladartha/portalum-pdf-generator:latest