name: Generate Licence

on:
  push:
    paths:
        - 'package.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run license-checker
      run: |
        npm install
        npm install -g license-checker
        license-checker --out ./LICENSE-thirdparty
    - name: Commit files
      run: |
        git config --local user.email "PortalumBot@portalum.eu"
        git config --local user.name "PortalumBot"
        git commit -m "[AUTO] Update license" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}